### ISSUE TITLE
UEFI VMs not working

### ISSUE THREAD

**Issue by slavachertanovo** [SaumonNet/proxmox-nixos#29] opened 2024-06-26 22:35 UTC
probably broken path:

> TASK ERROR: EFI base image '/usr/share/pve-edk2-firmware//OVMF_CODE.fd' not found

**Comment by JulienMalka** [comment] 2024-06-27 07:00
Duplicate of https://github.com/SaumonNet/proxmox-nixos/issues/14

**Comment by slavachertanovo** [comment] 2024-06-27 07:27
okay closing

**Closed** 2024-06-27 07:27 UTC
